FROM ubuntu:20.04
MAINTAINER Olivier RICARD <olivier+ansible@talkspirit.com>
RUN apt-get update && apt-get install -y python3-software-properties software-properties-common && \
    apt-get update && \
    apt-get install -y ansible python3 python3-apt python3-pycurl aptitude python3-pip python3-dev git jq curl
